name: exercice 2

on:
  workflow_dispatch:

env:
  a: 5
  b: -2

jobs:
  job_conditionnel:
    runs-on: ubuntu-latest
    if: (env.a >= 0) && (env.b >= 0)
    steps:
      - uses: actions/checkout@v2
      - name: Vérifier la condition
        run: echo "les valeurs a et b sont strictement positives"
