name: exercice 2

on:
  workflow_dispatch:

jobs:
  strategy:
    matrix:
      python-version: [3.6, 3.7, 3.8, 3.9]
  env:
  A: 5
  B: -2

  job_conditionnel:
    runs-on: ubuntu-latest
    if: (env.A >= 0) && (env.B >= 0)
    steps:
      - uses: actions/checkout@v2
      - name: Vérifier la condition
        run: echo "les valeurs a et b sont strictement positives"
