name: exercice 1

on:
  push:
    tags:
      - "release3*"

env:
  VAR1: hello

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher la variable
        run: |
          echo "La valeur de la variable est : $VAR1"

  job2:
    runs-on: ubuntu-latest
    if: faillure()

    steps:
      - name: Afficher le message d'erreur
        run: |
          echo "Le job précédent a malheureusement échoué, vous pouvez retenter votre chance la prochaine fois inchallah"
