name: exercice 1

on:
  push:
    tags:
      - "release11*"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher la variable
        run: |
          echo "La valeur de la variable est : ${{ vars.VAR1 }}"

  job2:
    runs-on: ubuntu-latest
    if: faillure()

    steps:
      - name: Afficher le message d'erreur
        run: |
          echo "Le job précédent a malheureusement échoué"
