name: exercice 2

on:
  workflow_dispatch:

env:
  A: 5
  B: 2

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Vérifier la condition
        if: ${{env.A >= 0 && env.B >= 0}}
        run: |
          echo "les valeurs a et b sont strictement positives"
